name             'kumapon-base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures k-base'
long_description 'Installs/Configures k-base'
version          '0.1.0'

depends          'apt', '~> 2.3.10'
depends          'acl'
depends          'build-essential'
depends          'logrotate'
depends          'git'
depends          'man'
depends          'rsync'
depends          'sudo', '~> 2.5.2'
depends          'vim'
depends          'users'
depends          'timezone-ii'
depends          'sysstat'
depends          'locale'
depends          'aws'
depends          'ulimit'
#depends          'monit'
